batch_nb_images: 4
css0: Olympus E-PL2
data_root: /home/skyu/p_CFA-filter/dataset/
epoch: -1
epochs: 300
filter0: linear
hsi: cave
interval: 10
keepcss: false
keepfilter: false
keepnetwork: false
loss: L1
loss_grad: 2
lsm: false
net: unet
nl_max: 30
nl_min: 0
noCommonNoise: false
noDA: false
noSkip: false
opt_css: RAdam
opt_demosaic: RAdam
opt_filter: RAdam
patch_size: 128
patches_per_image: 8
pattern: rggb
resume: false
sch: CosLR
seteps_per_epoch: 64
trainer: Simul
